# Generated by Django 5.2.13 on 2026-05-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_image_2_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Screenshot 3'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Screenshot 4'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Screenshot 5'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Screenshot 6'),
        ),
    ]
