# Generated by Django 5.2.13 on 2026-05-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_image_3_project_image_4_project_image_5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Screenshot 7'),
        ),
    ]
