from django.db import migrations


PROJECTS = [
    {
        "title": "AI Image Generation Project",
        "slug": "image-generation-project",
        "summary": "A generative AI project that creates visual assets from prompts and demonstrates practical image workflow ideas.",
        "description": "Visual content creation can take time when teams need multiple concepts, variations, or mockups. This project explores how image generation tools can quickly produce creative options while still requiring human review for quality, accuracy, and usefulness. The theme of this project is the Advanced Combat Exo (ACE) suit designed for military use by Shock & Awe Incorporated.",
        "category": "Generative AI",
        "tools_used": "AI Image Generation, Prompt Design, Visual Review, Creative Workflow, Engaging presentation construction",
        "key_features": "Prompt-based image creation\nMultiple generated image examples\nVisual comparison and review\nCreative workflow experimentation",
        "contribution": "I designed the prompts, provided reference images, generated visual outputs, and selected the strongest examples from the generated images to utilize in the presentation.",
        "challenges": "A key challenge was writing prompts that produced useful visuals while keeping the final images aligned with the intended idea and presentation style.",
        "lessons_learned": "I learned how small prompt changes can strongly affect image quality, composition, and usefulness, and why generated visuals need thoughtful human evaluation.",
        "image": "project_images/ACE_Suit_with_Model.png",
        "image_2": "project_images/Promotional_Mag2.png",
        "image_3": "project_images/Promotional_Magazine.png",
        "image_4": "project_images/ACE_overlay.png",
        "image_5": "project_images/ACE_insta_Post.png",
        "image_6": "",
        "image_7": "",
        "github_link": "",
        "demo_link": "",
        "is_featured": False,
    },
    {
        "title": "Campus SkillSwap Django Project",
        "slug": "campus-skillswap-django-project",
        "summary": "A Django web app that helps students connect and exchange useful campus skills.",
        "description": "Students often have valuable skills but do not have an easy way to connect with peers who need them. This project creates a platform where users can share skills and find learning opportunities.",
        "category": "Web Development",
        "tools_used": "Python, Django, SQLite, Bootstrap",
        "key_features": "User-friendly web interface\nDatabase-backed project structure\nSkill sharing concept\nOrganized page navigation\nStreamlined user-peer communication",
        "contribution": "I developed the Django app structure, built the pages, and worked on presenting information clearly to users.",
        "challenges": "One challenge was organizing the application so it remained simple and intuitive while still meeting the project requirements.",
        "lessons_learned": "I learned more about Django models, views, templates, and how to structure a full web application.",
        "image": "project_images/SkillSwapDash.png",
        "image_2": "project_images/SkillSwapBrowse.png",
        "image_3": "",
        "image_4": "",
        "image_5": "",
        "image_6": "",
        "image_7": "",
        "github_link": "https://github.com/AidanC6437/Django_LearningLog_Proj1",
        "demo_link": "https://aidanchiu-djangopt2-1.onrender.com/skills/",
        "is_featured": True,
    },
    {
        "title": "Chatbot Project",
        "slug": "chatbot-project",
        "summary": "A conversational AI assistant named Bruen designed to answer user questions in a helpful and organized way.",
        "description": "Many users need fast answers, but do not want to search through long documents or websites. This project provides a chatbot interface that can respond clearly and quickly to user needs.",
        "category": "AI Application",
        "tools_used": "Python, Django, OpenAI API, HTML, Bootstrap",
        "key_features": "Natural language question answering\nSimple chat-style interface\nClean response formatting\nWeb-based user experience\nUser-tailored responses",
        "contribution": "I designed the interface, connected the AI response flow, tested the chatbot behavior, and provided documents and context to train the AI.",
        "challenges": "One challenge was making responses feel useful and consistent while keeping the code simple.",
        "lessons_learned": "I learned how AI tools can be integrated into a web application and how prompt design affects response quality.",
        "image": "project_images/Chatbot_2.png",
        "image_2": "project_images/Chatbot_3.png",
        "image_3": "",
        "image_4": "",
        "image_5": "",
        "image_6": "",
        "image_7": "",
        "github_link": "",
        "demo_link": "https://www.chatbase.co/dashboard/aidan-chius-workspace/chatbot/ayoO81rceITdKHYe8DxOi/playground",
        "is_featured": False,
    },
    {
        "title": "Google AI Studio Media Project",
        "slug": "google-ai-studio-media-project",
        "summary": "A media-focused AI project that explores content creation and analysis using Google AI Studio.",
        "description": "Content teams often need faster ways to generate, review, or improve media assets while sacrificing minimal quality. This project uses Google AI Studio to experiment with media workflows and image generation.",
        "category": "Generative AI",
        "tools_used": "Google AI Studio, Prompt Engineering and Design, Media Generation Tools",
        "key_features": "AI-assisted media workflow\nPrompt-based content generation\nCreative experimentation\nPractical business use cases",
        "contribution": "I planned the workflow, tested prompts, re-engineered prompts to maximize quality and desired outputs, and evaluated how the generated media supported the project goals.",
        "challenges": "The biggest challenge was refining prompts so the results matched the intended tone and quality.",
        "lessons_learned": "I learned how prompt wording and structure strongly affect creative AI output and how to evaluate generated media more critically.",
        "image": "project_images/Assassin.jpg",
        "image_2": "project_images/GenEnvironment.png",
        "image_3": "",
        "image_4": "",
        "image_5": "",
        "image_6": "",
        "image_7": "",
        "github_link": "",
        "demo_link": "https://1drv.ms/v/c/34bc40a1dd1d3000/IQDJXHnbFBzVRrM9oj5WEKPWAert9QHH4iy4E-CgzefwwX0?e=hPhzRH",
        "is_featured": False,
    },
    {
        "title": "LangChain Agent Project",
        "slug": "langchain-agent-project",
        "summary": "A LangChain-based agent in Python that uses tools and reasoning steps to complete user tasks.",
        "description": "Standard chatbots can struggle with multi-step tasks that require tool use or structured reasoning. This project explores how an AI agent can make decisions, call tools, and return more useful answers.",
        "category": "AI Agent",
        "tools_used": "Python, LangChain, APIs, Prompt Engineering",
        "key_features": "Agent-style reasoning\nTool calling\nMulti-step response flow\nStructured output handling\nAgentic memory storage",
        "contribution": "I built the core logic via Python, installed the necessary libraries, tested prompts, and improved how the agent handled user requests.",
        "challenges": "A key challenge was understanding why the agent chose certain steps and adjusting prompts to improve results.",
        "lessons_learned": "I learned how agent frameworks organize tool usage and why guardrails matter in AI systems.",
        "image": "project_images/LangChainCode.png",
        "image_2": "project_images/LangChainRun2.png",
        "image_3": "",
        "image_4": "",
        "image_5": "",
        "image_6": "",
        "image_7": "",
        "github_link": "https://github.com/AidanC6437/ACLangChainAgentProject",
        "demo_link": "",
        "is_featured": True,
    },
    {
        "title": "Machine Learning Project (scikit-learn)",
        "slug": "machine-learning-project-scikit-learn",
        "summary": "A machine learning project that uses scikit-learn concepts in Python to analyze data and make predictions.",
        "description": "Organizations often need better ways to use data for decision-making. This project applies machine learning models to datasets so patterns can be identified and predictions can be made more effectively.",
        "category": "Machine Learning",
        "tools_used": "Python, pandas, scikit-learn, Jupyter Notebook",
        "key_features": "Data cleaning and preparation\nModel training / Machine Learning\nPrediction and evaluation\nClear presentation of results\nConfusion matrices / error evaluation",
        "contribution": "I prepared the datasets, selected the model, trained it, and reviewed its performance metrics.",
        "challenges": "It was challenging to choose the right features and explain model results in plain English.",
        "lessons_learned": "I learned how the machine learning workflow moves from raw data to evaluation and why model interpretation matters.",
        "image": "project_images/SciKit_Iris.png",
        "image_2": "project_images/SciKit_Cali_Housing.png",
        "image_3": "",
        "image_4": "",
        "image_5": "",
        "image_6": "",
        "image_7": "",
        "github_link": "https://github.com/2026-Spring-4V98/ml",
        "demo_link": "",
        "is_featured": False,
    },
    {
        "title": "N8N Agent Workflow Project",
        "slug": "n8n-agent-workflow-project",
        "summary": "An automated workflow that connects tools and AI steps to complete repetitive tasks with less manual work.",
        "description": "Businesses often waste time repeating the same digital tasks across multiple systems. This project uses N8N to connect triggers, logic, and AI-powered actions to streamline monotonous tasks.",
        "category": "Automation",
        "tools_used": "n8n, APIs, Webhooks, JSONS, AI Tools (i.e. Postman)",
        "key_features": "Trigger-based workflow execution\nTool-to-tool automation\nConditional logic steps\nAI-enhanced task routing\nJSON-based development",
        "contribution": "I designed the N8N workflow steps, connected the services, and tested the automation from start to finish.",
        "challenges": "The biggest challenge was debugging how data moved between workflow nodes and external services.",
        "lessons_learned": "I learned how automation platforms can reduce repetitive work and how careful testing improves workflow reliability.",
        "image": "project_images/AgentIntakeLabeled.png",
        "image_2": "project_images/AgentPricingLabeled.png",
        "image_3": "project_images/AgentSchedulingLabeled.png",
        "image_4": "project_images/AgentCommsLabeled.png",
        "image_5": "project_images/AgentOrchestratorLabeled.png",
        "image_6": "project_images/Handyman_form_xB3WjoW.png",
        "image_7": "project_images/HandymanEmailResult_tQ2isFU.png",
        "github_link": "",
        "demo_link": "",
        "is_featured": True,
    },
]


def seed_projects(apps, schema_editor):
    Project = apps.get_model("portfolio", "Project")
    for project in PROJECTS:
        Project.objects.update_or_create(slug=project["slug"], defaults=project)


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_project_image_7"),
    ]

    operations = [
        migrations.RunPython(seed_projects, migrations.RunPython.noop),
    ]
