from django.db import migrations


PROJECT_UPDATES = {
    "image-generation-project": {
        "title": "AI Image Generation Project",
        "summary": "A generative AI project that creates visual assets from prompts and demonstrates practical image workflow ideas.",
        "description": """Visual content creation can take time when teams need multiple concepts, variations, or mockups. This project explores how image generation tools can quickly produce creative options while still requiring human review for quality, accuracy, and usefulness. The theme of this project is the Advanced Combat Exo (ACE) suit designed for military use by my team and I: Shock & Awe Incorporated. Every image you will see is 100% generated by AI prompting, and you can even find the presentation in the 'Demo Link' under 'Project Details' if you're more interested in our work.""",
        "tools_used": "AI Image Generation, Prompt Design, Visual Review, Creative Workflow, Engaging presentation construction",
        "key_features": "Prompt-based image creation\nMultiple generated image examples\nVisual comparison and review\nCreative workflow experimentation",
        "contribution": """I designed the prompts, provided reference images, generated visual outputs, and selected the strongest examples from the generated images to utilize in our presentation. I also organized the project so viewers can see how effective AI usage can substantially increase the quality of AI-generated images, as well as improve the formatting and structure of the presentation.""",
        "challenges": """A key challenge was writing prompts that produced useful visuals while keeping the final images aligned with the intended idea and presentation style. Another key challenge was modifying the prompts, and thus slightly modifying some images so we didn't accidentally recreate copyrighted media. For instance, we couldn't just write "Let Indiana Jones fly across a chasm", we would have to write something like "Have a man resembling Harrison Ford wearing an adventurer outfit fly across a chasm." The resulting image wouldn't be 100% accurate, but it would be close enough. This issue was also present in the Google AI Studio Media Generation project I did.""",
        "lessons_learned": """I learned how small prompt changes can strongly affect image quality, composition, and usefulness, and why generated visuals need thoughtful human evaluation. I also learned that you could train your AI in a number of ways for it to understand your own thought process, and thus you give it context for how you want a certain image to be produced. Finally, my team and I learned how to manipulate AI prompting to navigate around the copyright infringement prevention guardrails most modern AI tools implement in order to generate our desired media.""",
    },
    "campus-skillswap-django-project": {
        "description": "Students often have valuable skills they learn in the early years of their career development, but do not have an easy way to connect with other peers who need them. This project, created with the use of AI Vibe Coding, solves that problem by creating a platform where users can share skills and find learning opportunities.",
        "key_features": "User-friendly web interface\nDatabase-backed project structure\nSkill sharing concept\nOrganized page navigation\nStreamlined user-peer communication",
        "contribution": "I developed the Django app structure, built the pages, and worked on presenting information clearly to users. I utilized AI Vibe Coding, alongside with my current Python skills, to help polish the application to meet a user-friendly and professional standard.",
        "challenges": "One challenge was organizing the application, so it remained simple and intuitive while still meeting the project requirements. I also struggled immensely with some formatting issues, as Django can be rigid sometimes in structuring things like text placement and images, so it was hard for me to make the web application professional as it currently is.",
        "lessons_learned": "I learned more about Django models, views, templates, and how to structure a full web application. I also learned how to properly train my AI for Vibe Coding purposes through sheer re-prompting and providing highly detailed website specifications to achieve my desired results. Turns out that the more specific details I gave the AI, the more likely it was to listen and execute its tasks properly.",
    },
    "chatbot-project": {
        "summary": "A conversational AI assistant named 'Bruen' designed to answer user questions in a helpful and organized way.",
        "description": "Many users need fast answers, but do not want to search through long documents or websites, like college course syllabi. This project solves that problem by providing a chatbot interface that can respond clearly and quickly to the user's desired needs. I even managed to insert some code on this website where you can use the chatbot by simply clicking the little icon on the bottom right of the screen. Feel free to give it a shot!",
        "contribution": "I designed the interface, connected the AI response flow, and tested the chatbot behavior. I was also responsible for providing the necessary documents/contexts to train the AI on what to use to execute its tasks. For instance, when I wanted to train Bruen to scan and summarize college course syllabi, I inserted some of my own course syllabi from my actual curriculum to train it on what to look for in said content and what exactly to summarize from it, based on what the user asks.",
        "challenges": "One challenge that I encountered during this project was making the responses feel useful and consistent while keeping the code simple. I also found it hard to make the AI more personable and less robotic due to all the different prompting I had to use to train it. Finally, in tangent with the training, training the chatbot surprisingly took a long time to have it provide viable responses based on what I wanted it to do.",
        "lessons_learned": "I learned how AI tools can be integrated into a web application and how prompt design affects response quality. I also learned that in order for an AI to effectively do its job, it takes many hours to simply retrain and configure its responses to achieve desired outcomes. In the world of AI, many hours of dedication and patience are required to maximize AI's full potential.",
    },
    "google-ai-studio-media-project": {
        "description": "Content teams, such as Media and Marketing departments in businesses, often need faster ways to generate, review, or improve media assets while sacrificing minimal quality. This fun project uses Google AI Studio to experiment with media workflows and image generation to demonstrate how AI can support creative production. I based this media off a popular video game series, 'Assassin's Creed.' You can view the full media video using the Demo Link within the 'Project Details' window to the right of the page. Sit back, grab a quick snack, and enjoy the show.",
        "tools_used": "Google AI Studio, Prompt Engineering and Design, Media Generation Tools",
        "contribution": "I planned the workflow, tested prompts, re-engineered prompts to maximize quality and desired outputs, and evaluated how the generated media supported the project goals.",
        "challenges": "The biggest challenge was refining prompts, so the results matched the intended tone and quality. The Google Gemini AI could be very difficult and indecisive when trying to interpret what I wanted from the prompts and sometimes decided to do things entirely differently. For instance, I would train my AI to generate text reading 'Session Terminated' and eventually it worked. However, when I tried making the AI print out the exact same media, it would just forget about its training and scramble the words again.",
        "lessons_learned": "I learned how prompt wording/structuring strongly affects creative AI output, and how to evaluate generated media more critically. It turns out that when it comes to AI-generated content, having the most specific-prompts possible and many hours of training can be necessary for an AI to produce truly amazing results.",
    },
    "langchain-agent-project": {
        "description": "Standard chatbots can struggle with multi-step tasks that require tool use or structured reasoning. For example, rudimentary AI chatbots may struggle with retrieving context clues from previous user prompts, which means it may forget what the user what initially asking about and thus have no idea what to help the user with. This project explores how an AI agent can make decisions, call tools, and return more useful answers through advanced coding techniques in Python.",
        "contribution": "I built the core logic via Python, installed the necessary libraries, tested prompts, and improved how the agent handled user requests. I was also responsible for establishing the AI's ability to store concepts in its memory to further user conversations and strengthen contextual applications in said conversations.",
        "challenges": "A key challenge I faced while constructing this LangChain Agent Project was understanding why the agent chose to execute certain steps and adjusting prompts to improve results. The agent decided to do its own thing every now and then, and it wasn't until I gave it very specific instructions on how to execute its tasks that it started to actually listen to me.",
        "lessons_learned": "I learned how agent frameworks organize tool usage and why guardrails matter in AI systems. I also learned how to make the Agent store user conversation topics so it can apply those topics in a contextual way, should a user refer to something else in a future prompt. I wholeheartedly believe that AI guardrails, whether revolving around its code, execution, or general ethics, are essential for the survival and further advancement of AI applications in the future.",
    },
    "machine-learning-project-scikit-learn": {
        "description": "Organizations often need better ways to use data for decision-making. Take the field of Consulting, for example. Consulting firms need to utilize massive amounts of data to make decisions and provide clients with value to help their firms grow, which can take a long time if done manually. This project applies a machine learning model to different datasets (i.e. California housing costs and flower iris patterns) so patterns can be identified and predictions can be made more effectively and efficiently.",
        "contribution": "I prepared the datasets, selected the appropriate AI model, trained it, and reviewed its performance metrics. I also modified some visuals, like heat maps and confusion matrices, and created 'Expected vs Prediction' target tables to more accurately represent the other results from the data (Ex. which patterns the model predicted wrong vs expected).",
        "challenges": "It was challenging to choose the right features and explain model results in plain English. I also found it difficult to code more and more visualizations for different uses, such as the values a model gets wrong and comparing expected vs predicted values from the model's work. In other words, the more code I tried inserting to try and maximize data visualizations, the harder my file became to interpret correctly without confusion.",
        "lessons_learned": "I learned how the machine learning workflow moves from raw data to evaluation, and why model interpretation matters. I also learned how to clearly see and modify particular code snippets to simplify the code as much as possible to prevent potential users and viewers from getting confused within the programming language. When it comes to AI model development, I found that most of the time having humility and being able to clearly explain why models work the way they do, is essential for one's learning and growth within the AI industry.",
    },
    "n8n-agent-workflow-project": {
        "description": "Businesses often waste time repeating the same digital tasks across multiple systems, such as returning an appointment request from a customer, which can be streamlined further to save time. This project addresses that problem by using workflow automation in N8N to connect triggers, logic, and AI-powered actions to streamline monotonous tasks for business leaders.",
        "contribution": "I designed the N8N workflow steps, connected the services, and tested the automation from start to finish. I even designed the Google Form to start the workflow and utilized AI to help me generate the desired email format to potential customers.",
        "challenges": "The biggest challenge I faced was debugging how data moved between workflow nodes and external services. During initial testing, almost every single time data flowed through the workflow, I encountered an error in nearly every single node. The other challenge was how to utilize Google Gemini AI to help me dynamically edit and return different data in different emails, depending on what the customer wanted.",
        "lessons_learned": "I learned how automation platforms can reduce repetitive work and how careful, meticulous testing improves workflow reliability. I also learned how to properly edit JSON code and manage interior AI prompting to achieve my desired results for a streamlined customer service.",
    },
}


def restore_full_project_text(apps, schema_editor):
    Project = apps.get_model("portfolio", "Project")
    for slug, fields in PROJECT_UPDATES.items():
        Project.objects.filter(slug=slug).update(**fields)


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_seed_project_data"),
    ]

    operations = [
        migrations.RunPython(restore_full_project_text, migrations.RunPython.noop),
    ]
